import 'package:flutter/material.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:flutter/src/widgets/placeholder.dart';

class Telecommunications extends StatefulWidget {
  const Telecommunications({super.key});

  @override
  State<Telecommunications> createState() => _TelecommunicationsState();
}

class _TelecommunicationsState extends State<Telecommunications> {
  bool _isExpanded = false;
  final List<Item> _items = <Item>[
    Item(
      headerValue: '   IoSyS',
      expandedValue:
          '►► Internet Of Things Systems & Services\n\n• The IoSyS option trains telecommunications engineers capable of orchestrating and developing IoT solutions while mastering the entire value chain\n\n• The IoSyS program is a crossroads of several technologies such as Big Data, Machine Learning, Embedded Systems, Web, Cloud, Fog, Networks, RFID, WSN, Security, etc\n\n• In this option, students will learn how to design and deploy IoT solutions, from the hardware components to the software and data analytics.',
    ),
    Item(
      headerValue: '   WIN',
      expandedValue:
          '►► Wireless Intelligent Networks\n\n• This option in Telecommunications is designed to provide students with the knowledge and skills necessary to excel in their professional and personal lives\n\n• It offers a unique combination of Data Science and Wireless Communication, two of the most in-demand and rapidly evolving fields in the world today\n\n• Students in this program will learn how to apply Data Science techniques to wireless communication systems, enabling them to analyze and make sense of the vast amounts of data generated by these systems. ',
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        return Scaffold(
          body: Container(
            decoration: BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter,
                colors: [
                  Color.fromARGB(255, 255, 137, 135)!,
                  Color.fromARGB(255, 60, 5, 5)!
                ],
              ),
            ),
            child: SingleChildScrollView(
              child: Center(
                child: Column(
                  children: [
                    SizedBox(height: 50.0),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Text(
                          'Telecommunications',
                          style: TextStyle(
                              fontSize:
                                  constraints.maxWidth < 600 ? 26.0 : 32.0,
                              fontWeight: FontWeight.bold,
                              fontFamily: 'Mukta Malar',
                              color: Colors.white),
                        ),
                      ],
                    ),
                    Image.asset(
                      'Assets/images/telecom.png',
                      width: constraints.maxWidth /
                          (constraints.maxWidth < 600 ? 1.5 : 1.17),
                      height: constraints.maxWidth < 600
                          ? constraints.maxHeight / 3
                          : constraints.maxHeight / 2.9,
                    ),
                    Container(
                      padding: EdgeInsets.all(16.0),
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          _buildContainerXL(
                            Icons.computer,
                            'TELECOMMUNICATIONS',
                            'Participate in the optimization of communication systems, from research to the design of equipment and services, through network infrastructure management.',
                          ),
                          SizedBox(height: 25.0),
                        ],
                      ),
                    ),
                    Container(
                      width: constraints.maxWidth /
                          (constraints.maxWidth < 600 ? 1.2 : 1.17),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(25.0),
                        boxShadow: [
                          BoxShadow(
                            color: Colors.grey.withOpacity(0.5),
                            spreadRadius: 2,
                            blurRadius: 5,
                            offset: Offset(0, 3),
                          ),
                        ],
                        color: Colors.white,
                      ),
                      child: Column(
                        children: [
                          SizedBox(height: 15.0),
                          Text(
                            'Options',
                            style: TextStyle(
                                fontSize:
                                    constraints.maxWidth < 600 ? 22.0 : 28.0,
                                fontWeight: FontWeight.bold,
                                fontFamily: 'Mukta Malar',
                                color: Color.fromARGB(255, 178, 0, 0)),
                          ),
                          SizedBox(height: 25.0),
                          ExpansionPanelList(
                            expansionCallback: (int index, bool isExpanded) {
                              setState(() {
                                _items[index].isExpanded = !isExpanded;
                              });
                            },
                            children: _items.map<ExpansionPanel>((Item item) {
                              return ExpansionPanel(
                                headerBuilder:
                                    (BuildContext context, bool isExpanded) {
                                  return ListTile(
                                    //leading: Icon(Icons.arrow_right),
                                    title: Text(item.headerValue,
                                        style: TextStyle(
                                            fontSize: 24.0,
                                            fontWeight: FontWeight.bold,
                                            fontFamily: 'Mukta Malar',
                                            color: Color.fromARGB(
                                                255, 122, 120, 120))),
                                  );
                                },
                                body: ListTile(
                                  title: Padding(
                                    padding: const EdgeInsets.only(
                                        top: 0.0,
                                        left: 12.0,
                                        right: 12.0,
                                        bottom: 12.0),
                                    child: Text(item.expandedValue,
                                        style: TextStyle(
                                            fontSize: 20.0,
                                            fontWeight: FontWeight.w500,
                                            fontFamily: 'Mukta Malar')),
                                  ),
                                ),
                                isExpanded: item.isExpanded,
                              );
                            }).toList(),
                          ),
                        ],
                      ),
                    ),
                    SizedBox(height: 25.0),
                  ],
                ),
              ),
            ),
          ),
        );
      },
    );
  }

  Widget _buildContainerXL(IconData iconData, String title, String text) {
    return Container(
      width: MediaQuery.of(context).size.width / 1.17,
      height: MediaQuery.of(context).size.height / 1.6,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(25.0),
        boxShadow: [
          BoxShadow(
            color: Colors.grey.withOpacity(0.5),
            spreadRadius: 2,
            blurRadius: 5,
            offset: Offset(0, 3),
          ),
        ],
        color: Colors.white,
      ),
      child: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(
                  iconData,
                  size: 40.0,
                  color: Color.fromARGB(255, 112, 0, 0),
                ),
                //Image.asset(imagePath, width: 40.0, height: 40.0),
                SizedBox(width: 15),
                Text(
                  title,
                  style: TextStyle(
                      fontSize: 28,
                      fontWeight: FontWeight.bold,
                      fontFamily: 'Mukta Malar',
                      color: Color.fromARGB(255, 178, 0, 0)),
                ),
              ],
            ),
            SizedBox(height: 15),
            Text(
              text,
              style: TextStyle(
                  fontSize: 24,
                  fontFamily: 'Mukta Malar',
                  fontWeight: FontWeight.w500,
                  color: Colors.grey[800]),
            ),
          ],
        ),
      ),
    );
  }
}

class Item {
  Item({
    required this.expandedValue,
    required this.headerValue,
    this.isExpanded = false,
  });

  String expandedValue;
  String headerValue;
  bool isExpanded;
}
